### ISSUE TITLE
statistical profiler is broken?

### ISSUE THREAD

**Issue by al-zatv** [vpelletier/pprofile#6]
looks like a bug in statistical profiler:

zatv@vostro-laptop:~/qqq$ pprofile --statistic 0.001 --out cachegrind.out.genData genData.py 
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/pprofile.py", line 739, in run
    sample(frame)
  File "/usr/local/lib/python2.7/dist-packages/pprofile.py", line 664, in sample
    called_timing, called_code, 0)
TypeError: call() takes exactly 7 arguments (6 given)

**Comment by vpelletier** [comment]
Woops, indeed this is a bug introduced in d1f9c31c50bc4a18ae803eed4da248dd1fe7defe . I fixed it in ecaaa74bbe7196d734d114fbb51814f952a24409 and released 1.8.1  on pypi.

Thanks a lot for the report, and sorry for not noticing the breakage before.
